builders:
  storage_helper_build:
    import: "package:storage_helper/builder.dart"
    builder_factories: ["storageHelperBuilder"]
    build_extensions: {".dart": ["model/storage_helper/storage_helper.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]