builders:
  storage_helper_build:
    import: "package:storage_helper_gen/builder.dart"
    builder_factories: ["storageHelperBuilder"]
    build_extensions: {".dart": ["storage_helper.g.dart"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]