name: storage_helper_gen
description: Generator for StorageHelper
version: 0.0.1
homepage: https://github.com/gabry2003/storage_helper

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.0.2
  source_gen: ^1.0.2

flutter:
