name: storage_helper
description: Package che permette di utilizzare FlutterSecureStorage con più tipi di dati
version: 0.0.1
homepage: https://github.com/gabry2003/storage_helper

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  storage_helper_gen:
    git:
      url: "https://github.com/gabry2003/storage_helper"
      path: storage_helper_gen
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.11
  intl: ^0.17.0

dependency_overrides:
  storage_helper_gen:
    path: ../storage_helper_gen

flutter:
